# Generated by Django 2.0.4 on 2018-04-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.TextField(blank=True, help_text='Name', null=True, verbose_name='Name of event'),
        ),
    ]
